/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openwebuiapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ToolModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ToolModel{}

// ToolModel struct for ToolModel
type ToolModel struct {
	Id string `json:"id"`
	UserId string `json:"user_id"`
	Name string `json:"name"`
	Content string `json:"content"`
	Specs []map[string]interface{} `json:"specs"`
	Meta ToolMeta `json:"meta"`
	AccessControl map[string]interface{} `json:"access_control,omitempty"`
	UpdatedAt int32 `json:"updated_at"`
	CreatedAt int32 `json:"created_at"`
}

type _ToolModel ToolModel

// NewToolModel instantiates a new ToolModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewToolModel(id string, userId string, name string, content string, specs []map[string]interface{}, meta ToolMeta, updatedAt int32, createdAt int32) *ToolModel {
	this := ToolModel{}
	this.Id = id
	this.UserId = userId
	this.Name = name
	this.Content = content
	this.Specs = specs
	this.Meta = meta
	this.UpdatedAt = updatedAt
	this.CreatedAt = createdAt
	return &this
}

// NewToolModelWithDefaults instantiates a new ToolModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewToolModelWithDefaults() *ToolModel {
	this := ToolModel{}
	return &this
}

// GetId returns the Id field value
func (o *ToolModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ToolModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ToolModel) SetId(v string) {
	o.Id = v
}

// GetUserId returns the UserId field value
func (o *ToolModel) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *ToolModel) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *ToolModel) SetUserId(v string) {
	o.UserId = v
}

// GetName returns the Name field value
func (o *ToolModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ToolModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ToolModel) SetName(v string) {
	o.Name = v
}

// GetContent returns the Content field value
func (o *ToolModel) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *ToolModel) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *ToolModel) SetContent(v string) {
	o.Content = v
}

// GetSpecs returns the Specs field value
func (o *ToolModel) GetSpecs() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.Specs
}

// GetSpecsOk returns a tuple with the Specs field value
// and a boolean to check if the value has been set.
func (o *ToolModel) GetSpecsOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Specs, true
}

// SetSpecs sets field value
func (o *ToolModel) SetSpecs(v []map[string]interface{}) {
	o.Specs = v
}

// GetMeta returns the Meta field value
func (o *ToolModel) GetMeta() ToolMeta {
	if o == nil {
		var ret ToolMeta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *ToolModel) GetMetaOk() (*ToolMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *ToolModel) SetMeta(v ToolMeta) {
	o.Meta = v
}

// GetAccessControl returns the AccessControl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ToolModel) GetAccessControl() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.AccessControl
}

// GetAccessControlOk returns a tuple with the AccessControl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ToolModel) GetAccessControlOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AccessControl) {
		return map[string]interface{}{}, false
	}
	return o.AccessControl, true
}

// HasAccessControl returns a boolean if a field has been set.
func (o *ToolModel) HasAccessControl() bool {
	if o != nil && !IsNil(o.AccessControl) {
		return true
	}

	return false
}

// SetAccessControl gets a reference to the given map[string]interface{} and assigns it to the AccessControl field.
func (o *ToolModel) SetAccessControl(v map[string]interface{}) {
	o.AccessControl = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ToolModel) GetUpdatedAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ToolModel) GetUpdatedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ToolModel) SetUpdatedAt(v int32) {
	o.UpdatedAt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ToolModel) GetCreatedAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ToolModel) GetCreatedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ToolModel) SetCreatedAt(v int32) {
	o.CreatedAt = v
}

func (o ToolModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ToolModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["user_id"] = o.UserId
	toSerialize["name"] = o.Name
	toSerialize["content"] = o.Content
	toSerialize["specs"] = o.Specs
	toSerialize["meta"] = o.Meta
	if o.AccessControl != nil {
		toSerialize["access_control"] = o.AccessControl
	}
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *ToolModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"user_id",
		"name",
		"content",
		"specs",
		"meta",
		"updated_at",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varToolModel := _ToolModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varToolModel)

	if err != nil {
		return err
	}

	*o = ToolModel(varToolModel)

	return err
}

type NullableToolModel struct {
	value *ToolModel
	isSet bool
}

func (v NullableToolModel) Get() *ToolModel {
	return v.value
}

func (v *NullableToolModel) Set(val *ToolModel) {
	v.value = val
	v.isSet = true
}

func (v NullableToolModel) IsSet() bool {
	return v.isSet
}

func (v *NullableToolModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToolModel(val *ToolModel) *NullableToolModel {
	return &NullableToolModel{value: val, isSet: true}
}

func (v NullableToolModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToolModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


