/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openwebuiapi

import (
	"encoding/json"
	"fmt"
)


// FeedbackFormData struct for FeedbackFormData
type FeedbackFormData struct {
	RatingData *RatingData
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *FeedbackFormData) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into RatingData
	err = json.Unmarshal(data, &dst.RatingData);
	if err == nil {
		jsonRatingData, _ := json.Marshal(dst.RatingData)
		if string(jsonRatingData) == "{}" { // empty struct
			dst.RatingData = nil
		} else {
			return nil // data stored in dst.RatingData, return on the first match
		}
	} else {
		dst.RatingData = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(FeedbackFormData)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *FeedbackFormData) MarshalJSON() ([]byte, error) {
	if src.RatingData != nil {
		return json.Marshal(&src.RatingData)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableFeedbackFormData struct {
	value *FeedbackFormData
	isSet bool
}

func (v NullableFeedbackFormData) Get() *FeedbackFormData {
	return v.value
}

func (v *NullableFeedbackFormData) Set(val *FeedbackFormData) {
	v.value = val
	v.isSet = true
}

func (v NullableFeedbackFormData) IsSet() bool {
	return v.isSet
}

func (v *NullableFeedbackFormData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeedbackFormData(val *FeedbackFormData) *NullableFeedbackFormData {
	return &NullableFeedbackFormData{value: val, isSet: true}
}

func (v NullableFeedbackFormData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeedbackFormData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


