/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QueryMemoryForm type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryMemoryForm{}

// QueryMemoryForm struct for QueryMemoryForm
type QueryMemoryForm struct {
	Content string `json:"content"`
	K NullableInt32 `json:"k,omitempty"`
}

type _QueryMemoryForm QueryMemoryForm

// NewQueryMemoryForm instantiates a new QueryMemoryForm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryMemoryForm(content string) *QueryMemoryForm {
	this := QueryMemoryForm{}
	this.Content = content
	return &this
}

// NewQueryMemoryFormWithDefaults instantiates a new QueryMemoryForm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryMemoryFormWithDefaults() *QueryMemoryForm {
	this := QueryMemoryForm{}
	return &this
}

// GetContent returns the Content field value
func (o *QueryMemoryForm) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *QueryMemoryForm) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *QueryMemoryForm) SetContent(v string) {
	o.Content = v
}

// GetK returns the K field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryMemoryForm) GetK() int32 {
	if o == nil || IsNil(o.K.Get()) {
		var ret int32
		return ret
	}
	return *o.K.Get()
}

// GetKOk returns a tuple with the K field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryMemoryForm) GetKOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.K.Get(), o.K.IsSet()
}

// HasK returns a boolean if a field has been set.
func (o *QueryMemoryForm) HasK() bool {
	if o != nil && o.K.IsSet() {
		return true
	}

	return false
}

// SetK gets a reference to the given NullableInt32 and assigns it to the K field.
func (o *QueryMemoryForm) SetK(v int32) {
	o.K.Set(&v)
}
// SetKNil sets the value for K to be an explicit nil
func (o *QueryMemoryForm) SetKNil() {
	o.K.Set(nil)
}

// UnsetK ensures that no value is present for K, not even an explicit nil
func (o *QueryMemoryForm) UnsetK() {
	o.K.Unset()
}

func (o QueryMemoryForm) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryMemoryForm) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["content"] = o.Content
	if o.K.IsSet() {
		toSerialize["k"] = o.K.Get()
	}
	return toSerialize, nil
}

func (o *QueryMemoryForm) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueryMemoryForm := _QueryMemoryForm{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQueryMemoryForm)

	if err != nil {
		return err
	}

	*o = QueryMemoryForm(varQueryMemoryForm)

	return err
}

type NullableQueryMemoryForm struct {
	value *QueryMemoryForm
	isSet bool
}

func (v NullableQueryMemoryForm) Get() *QueryMemoryForm {
	return v.value
}

func (v *NullableQueryMemoryForm) Set(val *QueryMemoryForm) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryMemoryForm) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryMemoryForm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryMemoryForm(val *QueryMemoryForm) *NullableQueryMemoryForm {
	return &NullableQueryMemoryForm{value: val, isSet: true}
}

func (v NullableQueryMemoryForm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryMemoryForm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


