/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SigninResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SigninResponse{}

// SigninResponse struct for SigninResponse
type SigninResponse struct {
	Id string `json:"id"`
	Email string `json:"email"`
	Name string `json:"name"`
	Role string `json:"role"`
	ProfileImageUrl string `json:"profile_image_url"`
	Token string `json:"token"`
	TokenType string `json:"token_type"`
}

type _SigninResponse SigninResponse

// NewSigninResponse instantiates a new SigninResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSigninResponse(id string, email string, name string, role string, profileImageUrl string, token string, tokenType string) *SigninResponse {
	this := SigninResponse{}
	this.Id = id
	this.Email = email
	this.Name = name
	this.Role = role
	this.ProfileImageUrl = profileImageUrl
	this.Token = token
	this.TokenType = tokenType
	return &this
}

// NewSigninResponseWithDefaults instantiates a new SigninResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSigninResponseWithDefaults() *SigninResponse {
	this := SigninResponse{}
	return &this
}

// GetId returns the Id field value
func (o *SigninResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SigninResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SigninResponse) SetId(v string) {
	o.Id = v
}

// GetEmail returns the Email field value
func (o *SigninResponse) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *SigninResponse) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *SigninResponse) SetEmail(v string) {
	o.Email = v
}

// GetName returns the Name field value
func (o *SigninResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SigninResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SigninResponse) SetName(v string) {
	o.Name = v
}

// GetRole returns the Role field value
func (o *SigninResponse) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *SigninResponse) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *SigninResponse) SetRole(v string) {
	o.Role = v
}

// GetProfileImageUrl returns the ProfileImageUrl field value
func (o *SigninResponse) GetProfileImageUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProfileImageUrl
}

// GetProfileImageUrlOk returns a tuple with the ProfileImageUrl field value
// and a boolean to check if the value has been set.
func (o *SigninResponse) GetProfileImageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProfileImageUrl, true
}

// SetProfileImageUrl sets field value
func (o *SigninResponse) SetProfileImageUrl(v string) {
	o.ProfileImageUrl = v
}

// GetToken returns the Token field value
func (o *SigninResponse) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *SigninResponse) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *SigninResponse) SetToken(v string) {
	o.Token = v
}

// GetTokenType returns the TokenType field value
func (o *SigninResponse) GetTokenType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenType
}

// GetTokenTypeOk returns a tuple with the TokenType field value
// and a boolean to check if the value has been set.
func (o *SigninResponse) GetTokenTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenType, true
}

// SetTokenType sets field value
func (o *SigninResponse) SetTokenType(v string) {
	o.TokenType = v
}

func (o SigninResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SigninResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["email"] = o.Email
	toSerialize["name"] = o.Name
	toSerialize["role"] = o.Role
	toSerialize["profile_image_url"] = o.ProfileImageUrl
	toSerialize["token"] = o.Token
	toSerialize["token_type"] = o.TokenType
	return toSerialize, nil
}

func (o *SigninResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"email",
		"name",
		"role",
		"profile_image_url",
		"token",
		"token_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSigninResponse := _SigninResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSigninResponse)

	if err != nil {
		return err
	}

	*o = SigninResponse(varSigninResponse)

	return err
}

type NullableSigninResponse struct {
	value *SigninResponse
	isSet bool
}

func (v NullableSigninResponse) Get() *SigninResponse {
	return v.value
}

func (v *NullableSigninResponse) Set(val *SigninResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSigninResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSigninResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSigninResponse(val *SigninResponse) *NullableSigninResponse {
	return &NullableSigninResponse{value: val, isSet: true}
}

func (v NullableSigninResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSigninResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


