/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserRoleUpdateForm type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserRoleUpdateForm{}

// UserRoleUpdateForm struct for UserRoleUpdateForm
type UserRoleUpdateForm struct {
	Id string `json:"id"`
	Role string `json:"role"`
}

type _UserRoleUpdateForm UserRoleUpdateForm

// NewUserRoleUpdateForm instantiates a new UserRoleUpdateForm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserRoleUpdateForm(id string, role string) *UserRoleUpdateForm {
	this := UserRoleUpdateForm{}
	this.Id = id
	this.Role = role
	return &this
}

// NewUserRoleUpdateFormWithDefaults instantiates a new UserRoleUpdateForm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserRoleUpdateFormWithDefaults() *UserRoleUpdateForm {
	this := UserRoleUpdateForm{}
	return &this
}

// GetId returns the Id field value
func (o *UserRoleUpdateForm) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UserRoleUpdateForm) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UserRoleUpdateForm) SetId(v string) {
	o.Id = v
}

// GetRole returns the Role field value
func (o *UserRoleUpdateForm) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *UserRoleUpdateForm) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *UserRoleUpdateForm) SetRole(v string) {
	o.Role = v
}

func (o UserRoleUpdateForm) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserRoleUpdateForm) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *UserRoleUpdateForm) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserRoleUpdateForm := _UserRoleUpdateForm{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserRoleUpdateForm)

	if err != nil {
		return err
	}

	*o = UserRoleUpdateForm(varUserRoleUpdateForm)

	return err
}

type NullableUserRoleUpdateForm struct {
	value *UserRoleUpdateForm
	isSet bool
}

func (v NullableUserRoleUpdateForm) Get() *UserRoleUpdateForm {
	return v.value
}

func (v *NullableUserRoleUpdateForm) Set(val *UserRoleUpdateForm) {
	v.value = val
	v.isSet = true
}

func (v NullableUserRoleUpdateForm) IsSet() bool {
	return v.isSet
}

func (v *NullableUserRoleUpdateForm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserRoleUpdateForm(val *UserRoleUpdateForm) *NullableUserRoleUpdateForm {
	return &NullableUserRoleUpdateForm{value: val, isSet: true}
}

func (v NullableUserRoleUpdateForm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserRoleUpdateForm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


