/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OpenWebuiAppsWebuiModelsUsersUserResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenWebuiAppsWebuiModelsUsersUserResponse{}

// OpenWebuiAppsWebuiModelsUsersUserResponse struct for OpenWebuiAppsWebuiModelsUsersUserResponse
type OpenWebuiAppsWebuiModelsUsersUserResponse struct {
	Id string `json:"id"`
	Email string `json:"email"`
	Name string `json:"name"`
	Role string `json:"role"`
	ProfileImageUrl string `json:"profile_image_url"`
}

type _OpenWebuiAppsWebuiModelsUsersUserResponse OpenWebuiAppsWebuiModelsUsersUserResponse

// NewOpenWebuiAppsWebuiModelsUsersUserResponse instantiates a new OpenWebuiAppsWebuiModelsUsersUserResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenWebuiAppsWebuiModelsUsersUserResponse(id string, email string, name string, role string, profileImageUrl string) *OpenWebuiAppsWebuiModelsUsersUserResponse {
	this := OpenWebuiAppsWebuiModelsUsersUserResponse{}
	this.Id = id
	this.Email = email
	this.Name = name
	this.Role = role
	this.ProfileImageUrl = profileImageUrl
	return &this
}

// NewOpenWebuiAppsWebuiModelsUsersUserResponseWithDefaults instantiates a new OpenWebuiAppsWebuiModelsUsersUserResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenWebuiAppsWebuiModelsUsersUserResponseWithDefaults() *OpenWebuiAppsWebuiModelsUsersUserResponse {
	this := OpenWebuiAppsWebuiModelsUsersUserResponse{}
	return &this
}

// GetId returns the Id field value
func (o *OpenWebuiAppsWebuiModelsUsersUserResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OpenWebuiAppsWebuiModelsUsersUserResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OpenWebuiAppsWebuiModelsUsersUserResponse) SetId(v string) {
	o.Id = v
}

// GetEmail returns the Email field value
func (o *OpenWebuiAppsWebuiModelsUsersUserResponse) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *OpenWebuiAppsWebuiModelsUsersUserResponse) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *OpenWebuiAppsWebuiModelsUsersUserResponse) SetEmail(v string) {
	o.Email = v
}

// GetName returns the Name field value
func (o *OpenWebuiAppsWebuiModelsUsersUserResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OpenWebuiAppsWebuiModelsUsersUserResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OpenWebuiAppsWebuiModelsUsersUserResponse) SetName(v string) {
	o.Name = v
}

// GetRole returns the Role field value
func (o *OpenWebuiAppsWebuiModelsUsersUserResponse) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *OpenWebuiAppsWebuiModelsUsersUserResponse) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *OpenWebuiAppsWebuiModelsUsersUserResponse) SetRole(v string) {
	o.Role = v
}

// GetProfileImageUrl returns the ProfileImageUrl field value
func (o *OpenWebuiAppsWebuiModelsUsersUserResponse) GetProfileImageUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProfileImageUrl
}

// GetProfileImageUrlOk returns a tuple with the ProfileImageUrl field value
// and a boolean to check if the value has been set.
func (o *OpenWebuiAppsWebuiModelsUsersUserResponse) GetProfileImageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProfileImageUrl, true
}

// SetProfileImageUrl sets field value
func (o *OpenWebuiAppsWebuiModelsUsersUserResponse) SetProfileImageUrl(v string) {
	o.ProfileImageUrl = v
}

func (o OpenWebuiAppsWebuiModelsUsersUserResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenWebuiAppsWebuiModelsUsersUserResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["email"] = o.Email
	toSerialize["name"] = o.Name
	toSerialize["role"] = o.Role
	toSerialize["profile_image_url"] = o.ProfileImageUrl
	return toSerialize, nil
}

func (o *OpenWebuiAppsWebuiModelsUsersUserResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"email",
		"name",
		"role",
		"profile_image_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenWebuiAppsWebuiModelsUsersUserResponse := _OpenWebuiAppsWebuiModelsUsersUserResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenWebuiAppsWebuiModelsUsersUserResponse)

	if err != nil {
		return err
	}

	*o = OpenWebuiAppsWebuiModelsUsersUserResponse(varOpenWebuiAppsWebuiModelsUsersUserResponse)

	return err
}

type NullableOpenWebuiAppsWebuiModelsUsersUserResponse struct {
	value *OpenWebuiAppsWebuiModelsUsersUserResponse
	isSet bool
}

func (v NullableOpenWebuiAppsWebuiModelsUsersUserResponse) Get() *OpenWebuiAppsWebuiModelsUsersUserResponse {
	return v.value
}

func (v *NullableOpenWebuiAppsWebuiModelsUsersUserResponse) Set(val *OpenWebuiAppsWebuiModelsUsersUserResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenWebuiAppsWebuiModelsUsersUserResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenWebuiAppsWebuiModelsUsersUserResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenWebuiAppsWebuiModelsUsersUserResponse(val *OpenWebuiAppsWebuiModelsUsersUserResponse) *NullableOpenWebuiAppsWebuiModelsUsersUserResponse {
	return &NullableOpenWebuiAppsWebuiModelsUsersUserResponse{value: val, isSet: true}
}

func (v NullableOpenWebuiAppsWebuiModelsUsersUserResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenWebuiAppsWebuiModelsUsersUserResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


